package com.andy.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CATEGORY".
 */
public class Category {

    private Long id;
    private String category_name;
    private Boolean is_pay;

    public Category() {
    }

    public Category(Long id) {
        this.id = id;
    }

    public Category(Long id, String category_name, Boolean is_pay) {
        this.id = id;
        this.category_name = category_name;
        this.is_pay = is_pay;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCategory_name() {
        return category_name;
    }

    public void setCategory_name(String category_name) {
        this.category_name = category_name;
    }

    public Boolean getIs_pay() {
        return is_pay;
    }

    public void setIs_pay(Boolean is_pay) {
        this.is_pay = is_pay;
    }

}
