package com.andy.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FUNDS".
 */
public class Funds {

    private Long id;
    private String funds_name;

    public Funds() {
    }

    public Funds(Long id) {
        this.id = id;
    }

    public Funds(Long id, String funds_name) {
        this.id = id;
        this.funds_name = funds_name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFunds_name() {
        return funds_name;
    }

    public void setFunds_name(String funds_name) {
        this.funds_name = funds_name;
    }

}
