package com.andy.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "PERSON".
 */
public class Person {

    private Long id;
    private String person_name;
    private Double num;

    public Person() {
    }

    public Person(Long id) {
        this.id = id;
    }

    public Person(Long id, String person_name, Double num) {
        this.id = id;
        this.person_name = person_name;
        this.num = num;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPerson_name() {
        return person_name;
    }

    public void setPerson_name(String person_name) {
        this.person_name = person_name;
    }

    public Double getNum() {
        return num;
    }

    public void setNum(Double num) {
        this.num = num;
    }

}
