package com.andy.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.andy.greendao.Record;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "RECORD".
 */
public class RecordDao extends AbstractDao<Record, Long> {

    public static final String TABLENAME = "RECORD";

    /**
     * Properties of entity Record.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Num = new Property(1, Double.class, "num", false, "NUM");
        public final static Property Date = new Property(2, java.util.Date.class, "date", false, "DATE");
        public final static Property Desc = new Property(3, String.class, "desc", false, "DESC");
        public final static Property Category = new Property(4, Integer.class, "category", false, "CATEGORY");
        public final static Property Funds = new Property(5, Integer.class, "funds", false, "FUNDS");
    }

    ;


    public RecordDao(DaoConfig config) {
        super(config);
    }

    public RecordDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "\"RECORD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NUM\" REAL," + // 1: num
                "\"DATE\" INTEGER," + // 2: date
                "\"DESC\" TEXT," + // 3: desc
                "\"CATEGORY\" INTEGER," + // 4: category
                "\"FUNDS\" INTEGER);"); // 5: funds
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RECORD\"";
        db.execSQL(sql);
    }

    /**
     * @inheritdoc
     */
    @Override
    protected void bindValues(SQLiteStatement stmt, Record entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        Double num = entity.getNum();
        if (num != null) {
            stmt.bindDouble(2, num);
        }

        java.util.Date date = entity.getDate();
        if (date != null) {
            stmt.bindLong(3, date.getTime());
        }

        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(4, desc);
        }

        Integer category = entity.getCategory();
        if (category != null) {
            stmt.bindLong(5, category);
        }

        Integer funds = entity.getFunds();
        if (funds != null) {
            stmt.bindLong(6, funds);
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    /**
     * @inheritdoc
     */
    @Override
    public Record readEntity(Cursor cursor, int offset) {
        Record entity = new Record( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
                cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1), // num
                cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)), // date
                cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // desc
                cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // category
                cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5) // funds
        );
        return entity;
    }

    /**
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor, Record entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNum(cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1));
        entity.setDate(cursor.isNull(offset + 2) ? null : new java.util.Date(cursor.getLong(offset + 2)));
        entity.setDesc(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setCategory(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setFunds(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
    }

    /**
     * @inheritdoc
     */
    @Override
    protected Long updateKeyAfterInsert(Record entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    /**
     * @inheritdoc
     */
    @Override
    public Long getKey(Record entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

}
