package com.andy.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "RECORD".
 */
public class Record {

    private Long id;
    private Double num;
    private java.util.Date date;
    private String desc;
    private Integer category;
    private Integer funds;

    public Record() {
    }

    public Record(Long id) {
        this.id = id;
    }

    public Record(Long id, Double num, java.util.Date date, String desc, Integer category, Integer funds) {
        this.id = id;
        this.num = num;
        this.date = date;
        this.desc = desc;
        this.category = category;
        this.funds = funds;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getNum() {
        return num;
    }

    public void setNum(Double num) {
        this.num = num;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public Integer getCategory() {
        return category;
    }

    public void setCategory(Integer category) {
        this.category = category;
    }

    public Integer getFunds() {
        return funds;
    }

    public void setFunds(Integer funds) {
        this.funds = funds;
    }

}
